
#Author: Shrikar Kalagi
#Date: 03/06/2019
server:
  port: 8080

spring:
  application:
    name: Application
  datasource:
    url: jdbc:postgresql://localhost:5432/telephone_directory
    username: postgres
    password: 12345
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
      javax:
        persistence:
          validation:
            mode: none




endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

